---
- name: Skip role if not enabled
  ansible.builtin.meta: end_role
  when: not chezmoi_enable

- name: Install chezmoi
  become: true
  community.general.pacman:
    name: chezmoi
    state: present

- name: Init and apply chezmoi
  ansible.builtin.command:
    cmd: chezmoi init --apply --ssh robert-sandor/.dotfiles --promptDefaults
    creates: ~/.local/share/chezmoi

- name: Ensure bat cache is updated
  ansible.builtin.command:
    cmd: bat cache --build
  changed_when: false
