---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: devbox

- name: Ensure ~/.ssh directory is present
  ansible.builtin.file:
    dest: ~/.ssh
    state: directory
    mode: "0700"

- name: Ensure SSH key is present for the user
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    comment: "{{ ansible_facts.user_id }}@{{ ansible_facts.hostname }}"
    type: ed25519
    mode: "0600"

- name: Update all packages # TODO: add a switch for this
  become: true
  community.general.pacman:
    upgrade: true
    update_cache: true

- name: Install essentials
  become: true
  community.general.pacman:
    state: present
    name:
      - bat
      - eza
      - man-db
      - fd
      - fish
      - fzf
      - git
      - git-delta
      - lazygit
      - ripgrep
      - starship
      - tmux
      - zoxide
