- name: Install neovim and some dependencies
  become: true
  community.general.pacman:
    name:
      - neovim
      - fzf
      - ripgrep
      - fd
      - lazygit
    state: present

- name: Clone neovim configuration # noqa: latest
  ansible.builtin.git:
    repo: git@github.com:robert-sandor/nvim.git # TODO: make variable ?
    dest: ~/.config/nvim
